# https://github.com/neosr-project/neosr/wiki/Installation-Instructions#manual-installation
# check dev
# cd neosr
# uv run --isolated train.py -opt ../super_resolution/train_8x.toml

name = "train_8x"
model_type = "image"
scale = 8
use_amp = true
bfloat16 = true
fast_matmul = true
#compile = true
#manual_seed = 1024

[datasets.train]
type = "paired"
dataroot_gt = 'D:/py/towl/fs/UKBiobankDataset/train/gt'
dataroot_lq = 'D:/py/towl/fs/UKBiobankDataset/train/lq/8x'
patch_size = 32
batch_size = 20
#accumulate = 1
augmentation = [ "none", "mixup", "resizemix" ]
aug_prob = [ 0.8, 0.1, 0.1 ]

[datasets.val]
name = "val"
type = "paired"
dataroot_gt = 'D:/py/towl/fs/UKBiobankDataset/val/gt'
dataroot_lq = 'D:/py/towl/fs/UKBiobankDataset/val/lq/8x'
save_img = true

[val]
val_freq = 1000
tile = -1
save_lq = true
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
[val.metrics.dists]
type = "calculate_dists"
better = "lower"
[val.metrics.topiq]
type = "calculate_topiq"

[path]
#pretrain_network_g = 'experiments\pretrain_g.pth'
#pretrain_network_d = 'experiments\pretrain_d.pth'

[network_g]
type = "hat_m"
#type = "hat_s"
#type = "hat_l"

[network_d]
type = "metagan"

[train]
ema = 0.999
wavelet_guided = true
wavelet_init = 80000
#sam = "fsam"
#sam_init = 1000
#eco = true
#eco_init = 15000
#match_lq = true

[train.optim_g]
type = "adan_sf"
lr = 2e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 1600

[train.optim_d]
type = "adan_sf"
lr = 2e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 600

#  losses
[train.mssim_opt]
type = "mssim_loss"
loss_weight = 1.0

[train.consistency_opt]
type = "consistency_loss"
loss_weight = 1.0

[train.ldl_opt]
type = "ldl_loss"
loss_weight = 1.0

[train.fdl_opt]
type = "fdl_loss"
model = "dinov2" # "vgg", "resnet", "effnet"
loss_weight = 0.75

[train.gan_opt]
type = "gan_loss"
gan_type = "bce"
loss_weight = 0.02

#[train.msswd_opt]
#type = "msswd_loss"
#loss_weight = 1.0

#[train.perceptual_opt]
#type = "vgg_perceptual_loss"
#loss_weight = 0.5
#criterion = "huber"
##patchloss = true
##ipk = true
##patch_weight = 1.0

#[train.dists_opt]
#type = "dists_loss"
#loss_weight = 0.5

#[train.ff_opt]
#type = "ff_loss"
#loss_weight = 0.35

#[train.ncc_opt]
#type = "ncc_loss"
#loss_weight = 1.0

#[train.kl_opt]
#type = "kl_loss"
#loss_weight = 1.0

[logger]
total_iter = 1000000
save_checkpoint_freq = 1000
use_tb_logger = true
#save_tb_img = true
print_freq = 100