[project]
name = "image-to-image"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.18",
    "pydicom>=3.0.1",
    "tomlkit>=0.13.3",
    "tqdm>=4.67.1",
]
