[project]
name = "ukb_dixon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "itk>=5.4.5",
    "numpy>=2.3.5",
    "pillow>=12.0.0",
    "pydicom>=3.0.1",
    "tomlkit>=0.13.3",
    "tqdm>=4.67.1",
]
