[project]
name = "ukb-mri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "itk>=5.4.5",
    "tomlkit>=0.13.3",
    "tqdm>=4.67.1",
]
